# Generated by Django 5.2.4 on 2025-12-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email_address',
            new_name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
