# Generated by Django 5.2.4 on 2026-06-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_order_options_rename_email_order_emailaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(help_text="Words user might type, e.g., 'vegan, dairy, allergy'", max_length=255)),
                ('answer', models.TextField(help_text='The exact answer the AI should give.')),
            ],
        ),
    ]
